// Master company database seed — the "build the list once, then check it every
// day" approach. Companies are grouped into the five focus buckets by HQ; the
// live-jobs country filter still surfaces a company's roles anywhere it hires.
//
//   [ name, site, bucket, sector, tier, visa, remote ]
//
//   visa   — sponsorship likelihood: yes | likely | unknown | no
//   remote — remote | hybrid | onsite | unknown
//
// IMPORTANT: ATS tokens are NOT guessed here. Only boards already proven live in
// this app carry one (see KNOWN_ATS). Every other row starts with ats = null and
// gets filled in by the probe endpoint, which asks each ATS whether a candidate
// slug resolves to a real board before saving it. That keeps the database honest
// — a token in the DB means it returned real jobs, not that it looked plausible.

const G = "germany", N = "netherlands", U = "uk", I = "india", R = "remote";
const BIG = "big-mnc", GROW = "growing-mnc", ST = "startup", FIN = "bank-finance", GOV = "gov-local";

export const SEED = [
  // ---------------------------------------------------------------- Germany
  ["SAP", "sap.com", G, "Enterprise Software", BIG, "yes", "hybrid"],
  ["Siemens", "siemens.com", G, "Industrial Tech", BIG, "yes", "hybrid"],
  ["Bosch", "bosch.com", G, "Industrial Tech", BIG, "yes", "hybrid"],
  ["Infineon", "infineon.com", G, "Semiconductors", BIG, "yes", "hybrid"],
  ["TeamViewer", "teamviewer.com", G, "SaaS", GROW, "likely", "hybrid"],
  ["Celonis", "celonis.com", G, "Process Mining", GROW, "yes", "hybrid"],
  ["Zalando", "zalando.com", G, "E-commerce", BIG, "yes", "hybrid"],
  ["HelloFresh", "hellofresh.com", G, "FoodTech", GROW, "yes", "hybrid"],
  ["Delivery Hero", "deliveryhero.com", G, "FoodTech", BIG, "yes", "hybrid"],
  ["N26", "n26.com", G, "Fintech", GROW, "yes", "hybrid"],
  ["Trade Republic", "traderepublic.com", G, "Fintech", GROW, "likely", "hybrid"],
  ["Solaris", "solarisgroup.com", G, "Fintech", GROW, "likely", "hybrid"],
  ["Raisin", "raisin.com", G, "Fintech", GROW, "likely", "hybrid"],
  ["SumUp", "sumup.com", G, "Fintech", GROW, "yes", "hybrid"],
  ["Taxfix", "taxfix.de", G, "Fintech", ST, "likely", "hybrid"],
  ["Moss", "getmoss.com", G, "Fintech", ST, "likely", "hybrid"],
  ["Pliant", "getpliant.com", G, "Fintech", ST, "unknown", "hybrid"],
  ["wefox", "wefox.com", G, "InsurTech", GROW, "likely", "hybrid"],
  ["ottonova", "ottonova.de", G, "InsurTech", ST, "unknown", "hybrid"],
  ["Personio", "personio.com", G, "HR Tech", GROW, "yes", "hybrid"],
  ["Zenjob", "zenjob.com", G, "HR Tech", ST, "likely", "hybrid"],
  ["CoachHub", "coachhub.com", G, "HR Tech", GROW, "likely", "remote"],
  ["Contentful", "contentful.com", G, "SaaS", GROW, "yes", "remote"],
  ["Sastrify", "sastrify.com", G, "SaaS", ST, "likely", "remote"],
  ["Adjust", "adjust.com", G, "AdTech", GROW, "yes", "hybrid"],
  ["GetYourGuide", "getyourguide.com", G, "Travel Tech", GROW, "yes", "hybrid"],
  ["trivago", "trivago.com", G, "Travel Tech", GROW, "yes", "hybrid"],
  ["Flix", "flix.com", G, "Mobility", GROW, "likely", "hybrid"],
  ["Forto", "forto.com", G, "Logistics Tech", ST, "likely", "hybrid"],
  ["sennder", "sennder.com", G, "Logistics Tech", GROW, "likely", "hybrid"],
  ["AUTO1 Group", "auto1-group.com", G, "E-commerce", GROW, "likely", "hybrid"],
  ["Scout24", "scout24.com", G, "Marketplaces", GROW, "likely", "hybrid"],
  ["idealo", "idealo.de", G, "Marketplaces", GROW, "likely", "hybrid"],
  ["CHECK24", "check24.de", G, "Marketplaces", GROW, "unknown", "onsite"],
  ["New Work SE (XING)", "new-work.se", G, "Marketplaces", GROW, "unknown", "hybrid"],
  ["Otto Group", "ottogroup.com", G, "E-commerce", BIG, "likely", "hybrid"],
  ["Grover", "getgrover.com", G, "E-commerce", ST, "likely", "hybrid"],
  ["Choco", "choco.com", G, "FoodTech", ST, "likely", "remote"],
  ["Enpal", "enpal.de", G, "Energy Tech", GROW, "unknown", "hybrid"],
  ["tado°", "tado.com", G, "Energy Tech", ST, "likely", "hybrid"],
  ["Babbel", "babbel.com", G, "EdTech", GROW, "yes", "hybrid"],
  ["Blinkist", "blinkist.com", G, "EdTech", ST, "likely", "hybrid"],
  ["ResearchGate", "researchgate.net", G, "Science Network", ST, "yes", "hybrid"],
  ["SoundCloud", "soundcloud.com", G, "Media", GROW, "yes", "hybrid"],
  ["Statista", "statista.com", G, "Data", GROW, "likely", "hybrid"],
  ["DeepL", "deepl.com", G, "AI", GROW, "yes", "remote"],
  ["Aleph Alpha", "aleph-alpha.com", G, "AI", ST, "likely", "hybrid"],
  ["Black Forest Labs", "bfl.ai", G, "AI", ST, "likely", "hybrid"],
  ["Parloa", "parloa.com", G, "AI", ST, "likely", "hybrid"],
  ["Helsing", "helsing.ai", G, "Defence AI", GROW, "likely", "hybrid"],
  ["KONUX", "konux.com", G, "IoT", ST, "likely", "hybrid"],
  ["Agile Robots", "agile-robots.com", G, "Robotics", GROW, "likely", "onsite"],
  ["Isar Aerospace", "isaraerospace.com", G, "Space", ST, "likely", "onsite"],
  ["Volocopter", "volocopter.com", G, "Mobility", ST, "likely", "onsite"],
  ["Deutsche Bank", "db.com", G, "Banking", FIN, "yes", "hybrid"],
  ["Commerzbank", "commerzbank.de", G, "Banking", FIN, "likely", "hybrid"],
  ["Allianz Technology", "allianz.com", G, "Insurance", FIN, "yes", "hybrid"],
  ["Munich Re", "munichre.com", G, "Insurance", FIN, "likely", "hybrid"],
  ["Lufthansa Group", "lufthansa.com", G, "Aviation", GOV, "likely", "hybrid"],

  // ------------------------------------------------------------ Netherlands
  ["Booking.com", "booking.com", N, "Travel Tech", BIG, "yes", "hybrid"],
  ["Adyen", "adyen.com", N, "Fintech", BIG, "yes", "hybrid"],
  ["Mollie", "mollie.com", N, "Fintech", GROW, "yes", "hybrid"],
  ["bunq", "bunq.com", N, "Fintech", GROW, "yes", "hybrid"],
  ["Backbase", "backbase.com", N, "Fintech", GROW, "yes", "hybrid"],
  ["Ohpen", "ohpen.com", N, "Fintech", ST, "likely", "hybrid"],
  ["Fourthline", "fourthline.com", N, "Fintech", ST, "likely", "hybrid"],
  ["Bird", "bird.com", N, "CPaaS", GROW, "yes", "remote"],
  ["Picnic", "picnic.app", N, "E-commerce", GROW, "yes", "hybrid"],
  ["Coolblue", "coolblue.nl", N, "E-commerce", GROW, "likely", "hybrid"],
  ["bol", "bol.com", N, "E-commerce", GROW, "likely", "hybrid"],
  ["Just Eat Takeaway", "justeattakeaway.com", N, "FoodTech", BIG, "yes", "hybrid"],
  ["TomTom", "tomtom.com", N, "Location Tech", GROW, "yes", "hybrid"],
  ["Philips", "philips.com", N, "HealthTech", BIG, "yes", "hybrid"],
  ["ASML", "asml.com", N, "Semiconductors", BIG, "yes", "onsite"],
  ["NXP Semiconductors", "nxp.com", N, "Semiconductors", BIG, "yes", "hybrid"],
  ["Nedap", "nedap.com", N, "IoT", GROW, "likely", "hybrid"],
  ["Exact", "exact.com", N, "SaaS", GROW, "likely", "hybrid"],
  ["AFAS Software", "afas.nl", N, "SaaS", GROW, "unknown", "hybrid"],
  ["Bynder", "bynder.com", N, "SaaS", GROW, "yes", "hybrid"],
  ["Mendix", "mendix.com", N, "Low-code", GROW, "yes", "hybrid"],
  ["WeTransfer", "wetransfer.com", N, "Media", GROW, "yes", "hybrid"],
  ["Framer", "framer.com", N, "Design SaaS", ST, "yes", "remote"],
  ["Miro", "miro.com", N, "Collaboration", BIG, "yes", "hybrid"],
  ["Catawiki", "catawiki.com", N, "Marketplaces", GROW, "yes", "hybrid"],
  ["Sendcloud", "sendcloud.com", N, "Logistics Tech", ST, "likely", "hybrid"],
  ["Channable", "channable.com", N, "MarTech", ST, "likely", "hybrid"],
  ["Studocu", "studocu.com", N, "EdTech", ST, "likely", "hybrid"],
  ["Tiqets", "tiqets.com", N, "Travel Tech", ST, "likely", "hybrid"],
  ["Otrium", "otrium.com", N, "E-commerce", ST, "likely", "hybrid"],
  ["Swapfiets", "swapfiets.nl", N, "Mobility", ST, "unknown", "hybrid"],
  ["Zivver", "zivver.com", N, "Security", ST, "likely", "hybrid"],
  ["Castor", "castoredc.com", N, "HealthTech", ST, "likely", "remote"],
  ["Leaseweb", "leaseweb.com", N, "Cloud Infra", GROW, "likely", "hybrid"],
  ["Recruitee", "recruitee.com", N, "HR Tech", ST, "likely", "remote"],
  ["Homerun", "homerun.co", N, "HR Tech", ST, "likely", "remote"],
  ["Nmbrs", "nmbrs.com", N, "HR Tech", ST, "unknown", "hybrid"],
  ["Optiver", "optiver.com", N, "Trading", FIN, "yes", "onsite"],
  ["IMC Trading", "imc.com", N, "Trading", FIN, "yes", "onsite"],
  ["Flow Traders", "flowtraders.com", N, "Trading", FIN, "yes", "onsite"],
  ["Da Vinci Derivatives", "davinciderivatives.com", N, "Trading", FIN, "yes", "onsite"],
  ["ING", "ing.com", N, "Banking", FIN, "yes", "hybrid"],
  ["ABN AMRO", "abnamro.com", N, "Banking", FIN, "likely", "hybrid"],
  ["Rabobank", "rabobank.com", N, "Banking", FIN, "likely", "hybrid"],
  ["Ahold Delhaize", "aholddelhaize.com", N, "Retail Tech", BIG, "likely", "hybrid"],
  ["KLM", "klm.com", N, "Aviation", GOV, "unknown", "hybrid"],
  ["Heineken", "theheinekencompany.com", N, "Consumer Tech", BIG, "likely", "hybrid"],

  // --------------------------------------------------------- United Kingdom
  ["Wise", "wise.com", U, "Fintech", GROW, "yes", "hybrid"],
  ["Monzo", "monzo.com", U, "Fintech", GROW, "yes", "remote"],
  ["Revolut", "revolut.com", U, "Fintech", BIG, "yes", "hybrid"],
  ["Starling Bank", "starlingbank.com", U, "Fintech", GROW, "likely", "hybrid"],
  ["Checkout.com", "checkout.com", U, "Fintech", GROW, "yes", "hybrid"],
  ["GoCardless", "gocardless.com", U, "Fintech", GROW, "yes", "hybrid"],
  ["TrueLayer", "truelayer.com", U, "Fintech", ST, "likely", "hybrid"],
  ["Thought Machine", "thoughtmachine.net", U, "Fintech", GROW, "yes", "hybrid"],
  ["Form3", "form3.tech", U, "Fintech", ST, "likely", "remote"],
  ["Modulr", "modulrfinance.com", U, "Fintech", ST, "likely", "hybrid"],
  ["Codat", "codat.io", U, "Fintech", ST, "likely", "hybrid"],
  ["Griffin", "griffin.com", U, "Fintech", ST, "likely", "remote"],
  ["Zilch", "zilch.com", U, "Fintech", ST, "likely", "hybrid"],
  ["Lendable", "lendable.co.uk", U, "Fintech", GROW, "likely", "hybrid"],
  ["Tide", "tide.co", U, "Fintech", GROW, "likely", "remote"],
  ["ClearBank", "clear.bank", U, "Fintech", GROW, "likely", "hybrid"],
  ["Zopa", "zopa.com", U, "Fintech", GROW, "likely", "hybrid"],
  ["Curve", "curve.com", U, "Fintech", ST, "likely", "hybrid"],
  ["Freetrade", "freetrade.io", U, "Fintech", ST, "unknown", "remote"],
  ["Moneybox", "moneyboxapp.com", U, "Fintech", ST, "unknown", "hybrid"],
  ["Cleo", "meetcleo.com", U, "Fintech", ST, "likely", "hybrid"],
  ["Wagestream", "wagestream.com", U, "Fintech", ST, "likely", "remote"],
  ["Marshmallow", "marshmallow.com", U, "InsurTech", ST, "likely", "hybrid"],
  ["ManyPets", "manypets.com", U, "InsurTech", ST, "unknown", "remote"],
  ["Zego", "zego.com", U, "InsurTech", ST, "likely", "hybrid"],
  ["Onfido", "onfido.com", U, "Identity", GROW, "yes", "hybrid"],
  ["ComplyAdvantage", "complyadvantage.com", U, "RegTech", GROW, "likely", "hybrid"],
  ["Quantexa", "quantexa.com", U, "Data / AI", GROW, "yes", "hybrid"],
  ["Featurespace", "featurespace.com", U, "Fraud / AI", ST, "likely", "hybrid"],
  ["Darktrace", "darktrace.com", U, "Security", GROW, "yes", "hybrid"],
  ["Snyk", "snyk.io", U, "Security", GROW, "yes", "remote"],
  ["Google DeepMind", "deepmind.google", U, "AI", BIG, "yes", "hybrid"],
  ["Stability AI", "stability.ai", U, "AI", ST, "likely", "remote"],
  ["Synthesia", "synthesia.io", U, "AI", GROW, "yes", "hybrid"],
  ["ElevenLabs", "elevenlabs.io", U, "AI", GROW, "likely", "remote"],
  ["PolyAI", "poly.ai", U, "AI", ST, "likely", "hybrid"],
  ["Tractable", "tractable.ai", U, "AI", ST, "likely", "hybrid"],
  ["Faculty", "faculty.ai", U, "AI", ST, "likely", "hybrid"],
  ["Graphcore", "graphcore.ai", U, "Semiconductors", GROW, "yes", "hybrid"],
  ["Arm", "arm.com", U, "Semiconductors", BIG, "yes", "hybrid"],
  ["Sage", "sage.com", U, "Enterprise Software", BIG, "likely", "hybrid"],
  ["Improbable", "improbable.io", U, "Gaming Tech", GROW, "yes", "hybrid"],
  ["Deliveroo", "deliveroo.co.uk", U, "FoodTech", GROW, "yes", "hybrid"],
  ["Gousto", "gousto.co.uk", U, "FoodTech", GROW, "likely", "hybrid"],
  ["Ocado Technology", "ocadogroup.com", U, "Retail Tech", GROW, "yes", "hybrid"],
  ["ASOS", "asos.com", U, "E-commerce", GROW, "likely", "hybrid"],
  ["Farfetch", "farfetch.com", U, "E-commerce", GROW, "likely", "hybrid"],
  ["Depop", "depop.com", U, "Marketplaces", ST, "likely", "hybrid"],
  ["Trainline", "thetrainline.com", U, "Travel Tech", GROW, "yes", "hybrid"],
  ["Skyscanner", "skyscanner.net", U, "Travel Tech", GROW, "yes", "hybrid"],
  ["Duffel", "duffel.com", U, "Travel Tech", ST, "likely", "hybrid"],
  ["Motorway", "motorway.co.uk", U, "Marketplaces", GROW, "likely", "remote"],
  ["carwow", "carwow.co.uk", U, "Marketplaces", ST, "likely", "hybrid"],
  ["Zoopla", "zoopla.co.uk", U, "PropTech", GROW, "unknown", "hybrid"],
  ["Rightmove", "rightmove.co.uk", U, "PropTech", GROW, "unknown", "hybrid"],
  ["Octopus Energy", "octopus.energy", U, "Energy Tech", GROW, "likely", "hybrid"],
  ["Paddle", "paddle.com", U, "SaaS", GROW, "likely", "remote"],
  ["Beamery", "beamery.com", U, "HR Tech", GROW, "likely", "hybrid"],
  ["Multiverse", "multiverse.io", U, "EdTech", GROW, "likely", "hybrid"],
  ["BBC", "bbc.co.uk", U, "Media", GOV, "likely", "hybrid"],

  // ------------------------------------------------------------------ India
  ["Razorpay", "razorpay.com", I, "Fintech", GROW, "no", "hybrid"],
  ["PhonePe", "phonepe.com", I, "Fintech", GROW, "no", "onsite"],
  ["Juspay", "juspay.in", I, "Fintech", GROW, "no", "hybrid"],
  ["Cashfree Payments", "cashfree.com", I, "Fintech", ST, "no", "hybrid"],
  ["Pine Labs", "pinelabs.com", I, "Fintech", GROW, "no", "hybrid"],
  ["Setu", "setu.co", I, "Fintech", ST, "no", "hybrid"],
  ["Groww", "groww.in", I, "Fintech", GROW, "no", "onsite"],
  ["Zerodha", "zerodha.com", I, "Fintech", GROW, "no", "onsite"],
  ["CRED", "cred.club", I, "Fintech", GROW, "no", "onsite"],
  ["Jupiter", "jupiter.money", I, "Fintech", ST, "no", "hybrid"],
  ["Fi Money", "fi.money", I, "Fintech", ST, "no", "hybrid"],
  ["Navi", "navi.com", I, "Fintech", GROW, "no", "onsite"],
  ["slice", "sliceit.com", I, "Fintech", ST, "no", "onsite"],
  ["BharatPe", "bharatpe.com", I, "Fintech", GROW, "no", "onsite"],
  ["KreditBee", "kreditbee.in", I, "Fintech", ST, "no", "onsite"],
  ["M2P Fintech", "m2pfintech.com", I, "Fintech", GROW, "no", "hybrid"],
  ["Perfios", "perfios.com", I, "Fintech", GROW, "no", "hybrid"],
  ["Signzy", "signzy.com", I, "Fintech", ST, "no", "remote"],
  ["Paytm", "paytm.com", I, "Fintech", BIG, "no", "onsite"],
  ["PolicyBazaar", "policybazaar.com", I, "InsurTech", GROW, "no", "onsite"],
  ["Swiggy", "swiggy.com", I, "FoodTech", BIG, "no", "hybrid"],
  ["Zomato", "zomato.com", I, "FoodTech", BIG, "no", "onsite"],
  ["Blinkit", "blinkit.com", I, "Quick Commerce", GROW, "no", "onsite"],
  ["Zepto", "zeptonow.com", I, "Quick Commerce", GROW, "no", "onsite"],
  ["Flipkart", "flipkart.com", I, "E-commerce", BIG, "no", "hybrid"],
  ["Myntra", "myntra.com", I, "E-commerce", GROW, "no", "hybrid"],
  ["Meesho", "meesho.com", I, "E-commerce", GROW, "no", "remote"],
  ["Nykaa", "nykaa.com", I, "E-commerce", GROW, "no", "hybrid"],
  ["Lenskart", "lenskart.com", I, "E-commerce", GROW, "no", "onsite"],
  ["udaan", "udaan.com", I, "B2B Commerce", GROW, "no", "onsite"],
  ["Delhivery", "delhivery.com", I, "Logistics Tech", GROW, "no", "hybrid"],
  ["CARS24", "cars24.com", I, "Marketplaces", GROW, "no", "onsite"],
  ["Spinny", "spinny.com", I, "Marketplaces", ST, "no", "onsite"],
  ["Urban Company", "urbancompany.com", I, "Marketplaces", GROW, "no", "hybrid"],
  ["Rapido", "rapido.bike", I, "Mobility", GROW, "no", "onsite"],
  ["Ola", "olacabs.com", I, "Mobility", GROW, "no", "onsite"],
  ["Dream11", "dream11.com", I, "Gaming", GROW, "no", "hybrid"],
  ["Games24x7", "games24x7.com", I, "Gaming", GROW, "no", "hybrid"],
  ["Freshworks", "freshworks.com", I, "SaaS", BIG, "likely", "hybrid"],
  ["Zoho", "zoho.com", I, "SaaS", BIG, "no", "onsite"],
  ["Chargebee", "chargebee.com", I, "SaaS", GROW, "likely", "remote"],
  ["BrowserStack", "browserstack.com", I, "DevTools", GROW, "likely", "remote"],
  ["Postman", "postman.com", I, "DevTools", GROW, "likely", "remote"],
  ["HackerRank", "hackerrank.com", I, "DevTools", GROW, "likely", "remote"],
  ["HackerEarth", "hackerearth.com", I, "DevTools", ST, "no", "remote"],
  ["Hasura", "hasura.io", I, "DevTools", ST, "likely", "remote"],
  ["Atlan", "atlan.com", I, "Data", ST, "likely", "remote"],
  ["MoEngage", "moengage.com", I, "MarTech", GROW, "likely", "hybrid"],
  ["CleverTap", "clevertap.com", I, "MarTech", GROW, "likely", "hybrid"],
  ["WebEngage", "webengage.com", I, "MarTech", ST, "no", "hybrid"],
  ["Whatfix", "whatfix.com", I, "SaaS", GROW, "likely", "hybrid"],
  ["Darwinbox", "darwinbox.com", I, "HR Tech", GROW, "no", "hybrid"],
  ["Zluri", "zluri.com", I, "SaaS", ST, "no", "remote"],
  ["Innovaccer", "innovaccer.com", I, "HealthTech", GROW, "likely", "hybrid"],
  ["HighRadius", "highradius.com", I, "Fintech SaaS", GROW, "likely", "hybrid"],
  ["Icertis", "icertis.com", I, "Enterprise SaaS", GROW, "likely", "hybrid"],
  ["Mindtickle", "mindtickle.com", I, "SaaS", GROW, "likely", "remote"],
  ["LeadSquared", "leadsquared.com", I, "SaaS", ST, "no", "hybrid"],
  ["Capillary Technologies", "capillarytech.com", I, "SaaS", ST, "no", "hybrid"],
  ["Uniphore", "uniphore.com", I, "AI", GROW, "likely", "hybrid"],
  ["Observe.AI", "observe.ai", I, "AI", ST, "likely", "remote"],
  ["Yellow.ai", "yellow.ai", I, "AI", GROW, "likely", "hybrid"],
  ["Gupshup", "gupshup.io", I, "CPaaS", GROW, "likely", "hybrid"],
  ["Exotel", "exotel.com", I, "CPaaS", ST, "no", "hybrid"],
  ["Sprinklr", "sprinklr.com", I, "SaaS", BIG, "likely", "hybrid"],
  ["Druva", "druva.com", I, "Cloud Infra", GROW, "likely", "hybrid"],
  ["InMobi", "inmobi.com", I, "AdTech", GROW, "likely", "hybrid"],
  ["upGrad", "upgrad.com", I, "EdTech", GROW, "no", "hybrid"],
  ["PhysicsWallah", "pw.live", I, "EdTech", GROW, "no", "onsite"],
  ["Unacademy", "unacademy.com", I, "EdTech", GROW, "no", "hybrid"],

  // ----------------------------------------------------------------- Remote
  ["GitLab", "gitlab.com", R, "DevTools", BIG, "n/a", "remote"],
  ["Automattic", "automattic.com", R, "Web / CMS", BIG, "n/a", "remote"],
  ["Canonical", "canonical.com", R, "Linux / Cloud", GROW, "n/a", "remote"],
  ["Elastic", "elastic.co", R, "Search / Data", BIG, "n/a", "remote"],
  ["Grafana Labs", "grafana.com", R, "Observability", GROW, "n/a", "remote"],
  ["HashiCorp", "hashicorp.com", R, "Infra", BIG, "n/a", "remote"],
  ["GitHub", "github.com", R, "DevTools", BIG, "n/a", "remote"],
  ["Sourcegraph", "sourcegraph.com", R, "DevTools", ST, "n/a", "remote"],
  ["Vercel", "vercel.com", R, "DevTools", GROW, "n/a", "remote"],
  ["Netlify", "netlify.com", R, "DevTools", GROW, "n/a", "remote"],
  ["Supabase", "supabase.com", R, "Databases", ST, "n/a", "remote"],
  ["PostHog", "posthog.com", R, "Analytics", ST, "n/a", "remote"],
  ["Cal.com", "cal.com", R, "SaaS", ST, "n/a", "remote"],
  ["Prisma", "prisma.io", R, "DevTools", ST, "n/a", "remote"],
  ["Strapi", "strapi.io", R, "CMS", ST, "n/a", "remote"],
  ["Appwrite", "appwrite.io", R, "Backend / BaaS", ST, "n/a", "remote"],
  ["Mattermost", "mattermost.com", R, "Collaboration", ST, "n/a", "remote"],
  ["Rocket.Chat", "rocket.chat", R, "Collaboration", ST, "n/a", "remote"],
  ["Discourse", "discourse.org", R, "Community", ST, "n/a", "remote"],
  ["Zulip", "zulip.com", R, "Collaboration", ST, "n/a", "remote"],
  ["Zapier", "zapier.com", R, "Automation", GROW, "n/a", "remote"],
  ["Buffer", "buffer.com", R, "Social SaaS", ST, "n/a", "remote"],
  ["Doist", "doist.com", R, "Productivity", ST, "n/a", "remote"],
  ["Toggl", "toggl.com", R, "Productivity", ST, "n/a", "remote"],
  ["Aha!", "aha.io", R, "Product SaaS", ST, "n/a", "remote"],
  ["Close", "close.com", R, "CRM", ST, "n/a", "remote"],
  ["Ghost", "ghost.org", R, "Publishing", ST, "n/a", "remote"],
  ["Chili Piper", "chilipiper.com", R, "SaaS", ST, "n/a", "remote"],
  ["Remote", "remote.com", R, "HR Tech", GROW, "n/a", "remote"],
  ["Deel", "deel.com", R, "HR Tech", GROW, "n/a", "remote"],
  ["Oyster", "oysterhr.com", R, "HR Tech", ST, "n/a", "remote"],
  ["Turing", "turing.com", R, "Talent Marketplace", GROW, "n/a", "remote"],
  ["Toptal", "toptal.com", R, "Talent Marketplace", GROW, "n/a", "remote"],
  ["Andela", "andela.com", R, "Talent Marketplace", GROW, "n/a", "remote"],
  ["Arc.dev", "arc.dev", R, "Talent Marketplace", ST, "n/a", "remote"],
  ["X-Team", "x-team.com", R, "Talent Marketplace", ST, "n/a", "remote"],
  ["Crossover", "crossover.com", R, "Talent Marketplace", GROW, "n/a", "remote"],
  ["Clevertech", "clevertech.biz", R, "Consultancy", ST, "n/a", "remote"],
  ["10up", "10up.com", R, "Consultancy", ST, "n/a", "remote"],
  ["DuckDuckGo", "duckduckgo.com", R, "Search / Privacy", ST, "n/a", "remote"],
  ["Mozilla", "mozilla.org", R, "Browsers", GROW, "n/a", "remote"],
  ["Wikimedia Foundation", "wikimediafoundation.org", R, "Non-profit Tech", GROW, "n/a", "remote"],
  ["Nord Security", "nordsecurity.com", R, "Security", GROW, "n/a", "remote"],
  ["Kraken", "kraken.com", R, "Crypto", GROW, "n/a", "remote"],
  ["Hugging Face", "huggingface.co", R, "AI", GROW, "n/a", "remote"],
  ["Replicate", "replicate.com", R, "AI", ST, "n/a", "remote"],
  ["Weights & Biases", "wandb.ai", R, "AI", GROW, "n/a", "remote"],
  ["Modal", "modal.com", R, "AI Infra", ST, "n/a", "remote"],
  ["Stripe", "stripe.com", R, "Fintech", BIG, "n/a", "remote"],
  ["Datadog", "datadoghq.com", R, "Observability", BIG, "n/a", "hybrid"],
  ["MongoDB", "mongodb.com", R, "Databases", BIG, "n/a", "hybrid"],
  ["Cloudflare", "cloudflare.com", R, "Infra / Security", BIG, "n/a", "hybrid"],
  ["DigitalOcean", "digitalocean.com", R, "Cloud Infra", GROW, "n/a", "remote"],
  ["Twilio", "twilio.com", R, "CPaaS", BIG, "n/a", "remote"],
  ["Okta", "okta.com", R, "Identity", BIG, "n/a", "remote"],
  ["Dropbox", "dropbox.com", R, "SaaS", BIG, "n/a", "remote"],
  ["Airtable", "airtable.com", R, "SaaS", GROW, "n/a", "remote"],
  ["Asana", "asana.com", R, "SaaS", BIG, "n/a", "hybrid"],
  ["Figma", "figma.com", R, "Design SaaS", BIG, "n/a", "hybrid"],
  ["Coinbase", "coinbase.com", R, "Crypto", BIG, "n/a", "remote"],
  ["Shopify", "shopify.com", R, "E-commerce", BIG, "n/a", "remote"],
];

// Boards already proven live in this app — the ONLY tokens seeded, because each
// one is known to return real jobs from the Greenhouse API today.
export const KNOWN_ATS = {
  Stripe: ["greenhouse", "stripe"],
  Datadog: ["greenhouse", "datadog"],
  MongoDB: ["greenhouse", "mongodb"],
  Adyen: ["greenhouse", "adyen"],
  GitLab: ["greenhouse", "gitlab"],
  Twilio: ["greenhouse", "twilio"],
  Elastic: ["greenhouse", "elastic"],
  Okta: ["greenhouse", "okta"],
  Figma: ["greenhouse", "figma"],
  Postman: ["greenhouse", "postman"],
  PhonePe: ["greenhouse", "phonepe"],
  Vercel: ["greenhouse", "vercel"],
  Airtable: ["greenhouse", "airtable"],
  Asana: ["greenhouse", "asana"],
  Dropbox: ["greenhouse", "dropbox"],
  Cloudflare: ["greenhouse", "cloudflare"],
  Monzo: ["greenhouse", "monzo"],
  GoCardless: ["greenhouse", "gocardless"],
  N26: ["greenhouse", "n26"],
  Celonis: ["greenhouse", "celonis"],
  GetYourGuide: ["greenhouse", "getyourguide"],
  HelloFresh: ["greenhouse", "hellofresh"],
  Contentful: ["greenhouse", "contentful"],
  SumUp: ["greenhouse", "sumup"],
  Coinbase: ["greenhouse", "coinbase"],
  // Workday tokens are "tenant:datacenter:site". These three were confirmed by
  // brute-forcing the grid and checking the returned job URLs resolve; the
  // probe can still discover more, but guessing them is expensive so the known
  // ones are seeded.
  Philips: ["workday", "philips:wd3:jobs-and-careers"],
  "NXP Semiconductors": ["workday", "nxp:wd3:Careers"],
  Rabobank: ["workday", "rabobank:wd3:Jobs"],
};

// Slug used for probing ATS boards and as the stable DB key.
export function slugify(name = "") {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // strip accents: "tado°" / "Zürich" → ascii
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Candidate ATS slugs to try for a company: "Just Eat Takeaway" → justeattakeaway,
// just-eat-takeaway, justeat…; plus the bare domain label.
export function slugCandidates(name = "", site = "") {
  const base = slugify(name);
  const domain = (site || "").replace(/^www\./, "").split(".")[0];
  const out = [base, base.replace(/-/g, ""), domain, slugify(domain)];
  return [...new Set(out.filter((s) => s && s.length > 1))];
}

export const SEED_COLUMNS = ["name", "site", "bucket", "sector", "tier", "visa", "remote"];
